# Generated by Django 6.0 on 2025-12-16 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_transaction_options_transaction_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(default='GHS', max_length=10),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(default='GHS', max_length=10),
        ),
    ]
