# Generated by Django 6.0 on 2025-12-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='reminder_days_before',
            field=models.PositiveIntegerField(default=2, help_text='Days before next payment to send reminder SMS'),
        ),
    ]
