# Generated by Django 6.0 on 2026-01-21 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_subscription_reminder_days_before'),
        ('projects', '0003_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='enable_reminders',
            field=models.BooleanField(default=True, help_text='Enable SMS reminders for this subscription'),
        ),
        migrations.AddIndex(
            model_name='account',
            index=models.Index(fields=['user', 'is_active'], name='finance_acc_user_id_11c77c_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'status'], name='finance_sub_user_id_c57932_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['user', 'next_payment_date'], name='finance_sub_user_id_868e00_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['account', 'next_payment_date'], name='finance_sub_account_735380_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='finance_tra_user_id_3294c0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 't_type'], name='finance_tra_user_id_c19dd3_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'category'], name='finance_tra_user_id_5b4ec6_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='finance_tra_account_588697_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['project', 'date'], name='finance_tra_project_f3fc61_idx'),
        ),
    ]
