# Generated by Django 6.0 on 2025-12-16 00:56

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Upload a profile picture (JPEG, PNG, GIF, BMP, WEBP). Minimum 50x50px, maximum 10MB.', null=True, upload_to='avatars/', validators=[accounts.models.validate_image]),
        ),
    ]
