# Generated by Django 6.0 on 2025-12-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='E.164 format recommended, e.g., +233XXXXXXXXX', max_length=20),
        ),
    ]
