# Generated by Django 6.0 on 2026-01-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userprofile_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_currency',
            field=models.CharField(default='GHS', help_text='Default currency for new transactions and subscriptions', max_length=10),
        ),
    ]
