# Generated by Django 6.0 on 2025-12-25 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='reminder_minutes_before',
            field=models.PositiveIntegerField(default=120, help_text='Minutes before deadline to send SMS reminder'),
        ),
    ]
