# Generated by Django 6.0 on 2026-01-21 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['owner', 'progress'], name='learning_co_owner_i_fb60a1_idx'),
        ),
    ]
