# Generated by Django 6.0 on 2025-12-25 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('subscription', 'Subscription'), ('task', 'Task')], max_length=20)),
                ('object_id', models.PositiveIntegerField()),
                ('reminder_for_date', models.DateTimeField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('response_detail', models.JSONField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', 'reminder_for_date'], name='notificatio_content_09c012_idx'), models.Index(fields=['user', 'reminder_type', 'sent_at'], name='notificatio_user_id_22ec86_idx')],
                'unique_together': {('content_type', 'object_id', 'reminder_for_date')},
            },
        ),
    ]
